apiVersion: 1
prune: true

datasources:
  - name: CloudWatch
    uid: cloudwatch
    type: cloudwatch
    access: proxy
    isDefault: true
    jsonData:
      authType: default
      defaultRegion: __AWS_REGION__
