{
 "title": "ERPx",
 "description": "ERPx dashbaord",
 "tags": [
  "loki",
  "mule",
  "erpx"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "ERPx berichten per zender (excl. PROEF)",
   "type": "stat",
   "description": "Aantal ERPx berichten per zender, PROEF-zendingen uitgesloten.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (zender) (\n  count_over_time(\n    {service_name=\"mule\"}\n    | json\n    | applicationName =~ \"planon-eapi|energiemissie-eapi|ltc-eapi|easyfunders-eapi|fis-nijm-eadap|power2pay-padap|fis-nijm-papi\"\n    | content_zender != \"\" and content_zender !~ \"(?i)PROEF\"\n    | label_format zender=content_zender\n    [$__interval]\n  )\n)",
     "legendFormat": "{{zender}}"
    }
   ]
  },
  {
   "title": "ERPx fouten berichen per zender (excl. PROEF)",
   "type": "stat",
   "description": "Aantal correlation IDs met een ERROR, gegroepeerd per zender.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(correlationId) (\n  count_over_time(\n    {service_name=\"mule\"} \n    | json \n    | applicationName =~ `planon-eapi|energiemissie-eapi|ltc-eapi|easyfunders-eapi|fis-nijm-eadap|power2pay-padap|fis-nijm-papi` \n    | priority = `ERROR` \n    [$__range]\n  )   \n)",
     "legendFormat": "{{correlationId}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (zender, correlationId) (\n  count_over_time(\n    {service_name=\"mule\"}\n    | json\n    | applicationName =~ \"planon-eapi|energiemissie-eapi|ltc-eapi|easyfunders-eapi|fis-nijm-eadap|power2pay-padap|fis-nijm-papi\"\n    | content_zender != \"\" and content_zender !~ \"(?i)PROEF\"\n    | label_format zender=content_zender\n    [$__range]\n  )\n)",
     "legendFormat": "{{zender}}"
    }
   ]
  },
  {
   "title": "ERPx foutenlijst (error detail table)",
   "type": "table",
   "description": "Foutmeldingen per correlation ID, verrijkt met de zender van het bericht.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(correlationId, content_description) (\n  count_over_time(\n    {service_name=\"mule\"} \n    | json\n    | priority = `ERROR` \n    | (applicationName =~ `.*energiemissie-eapi.*|.*planon-eapi.*|.*ltc-eapi.*|.*easyfunders-eapi.*|.*fis-nijm-eadap.*|.*power2pay-padap.*|.*erpx-nijm-sapi.*`)\nor (applicationName =~ `.*fis-nijm-papi.*` and message =~ `bestandsnaam`) or (applicationName =~ `.*fis-nijm-papi.*` and content_description != \"\")\n    [$__range]\n  )   \n)",
     "legendFormat": "{{correlationId}}"
    },
    {
     "direction": "backward",
     "expr": "sum by (zender, correlationId) (\n  count_over_time(\n    {service_name=\"mule\"}\n    | json\n    | applicationName =~ \"planon-eapi|energiemissie-eapi|ltc-eapi|easyfunders-eapi|fis-nijm-eadap|power2pay-padap|fis-nijm-papi\"\n    | content_zender != \"\" and content_zender !~ \"(?i)PROEF\"\n    | label_format zender=content_zender\n    [$__range]\n  )\n)",
     "legendFormat": "{{zender}}"
    }
   ]
  }
 ]
}